apiVersion: apps/v1
kind: Deployment
metadata:
  name: testjenkins-webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 235447109042.dkr.ecr.us-west-2.amazonaws.com/generic-repository:latest
        ports:
        - containerPort: 80